Link additional required LLVM libraries
Without these additional required dependencies, linking fails with errors such as:
`undefined reference to llvm::errs()'`