Link more required LLVM libraries
Without these additional required dependencies, linking fails with errors such as:
```
in function `amd_comgr_index_list_metadata':
<artificial>:(.text+0x4d4c): undefined reference to `llvm::msgpack::ArrayDocNode::operator[](unsigned long)'
```
and
```
undefined reference to `llvm::msgpack::Document::fromYAML(llvm::StringRef)'
```